export enum Runtime {
  BROWSER = "BROWSER",
  I_FRAME = "I_FRAME",
  NODE_JS = "NODE_JS",
  NODE_LOADER = "NODE_LOADER",
  WEB_WORKER = "WEB_WORKER",
  SERVICE_WORKER = "SERVICE_WORKER",
  TEST_ENVIRONMENT = "TEST_ENVIRONMENT",
}
